# docker-compose.yml
version: '3.8'
services:

  neo4j:
    image: neo4j:latest
    container_name: meloc-neo4j
    ports:
      - '7474:7474'   # Browser UI
      - '7687:7687'   # Bolt
    environment:
      # tek satırda kullanıcı/şifre
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile   # backend klasöründe bir Dockerfile olmalı
    container_name: meloc-backend
    ports:
      - '5000:5000'
    depends_on:
      - neo4j
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev  # veya production için `npm start`

volumes:
  neo4j_data:
  neo4j_logs:
